steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$valued-aquifer-426117-c0/fastapi-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$valued-aquifer-426117-c0/fastapi-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'fastapi-app', '--image', 'gcr.io/$valued-aquifer-426117-c0/fastapi-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/$valued-aquifer-426117-c0/fastapi-app'
